export type PresetCategory = {
  id: string;
  label: string;
  items: string[];
};

export const REQUIREMENT_CATEGORIES: PresetCategory[] = [
  {
    id: 'general',
    label: 'Generales',
    items: [
      'Mayor de edad',
      'Cedula vigente',
      'Disponibilidad inmediata',
      'Disponibilidad de horario',
      'Disponibilidad para fines de semana',
      'Disponibilidad para dias feriados',
      'Disponibilidad para turnos rotativos',
      'Buena presentacion personal',
      'Puntualidad',
      'Responsabilidad',
      'Honestidad',
      'Trabajo en equipo',
      'Buena comunicacion verbal',
      'Orientacion al servicio',
      'Curriculum actualizado',
      'Referencias laborales comprobables',
    ],
  },
  {
    id: 'ventas',
    label: 'Ventas',
    items: [
      'Experiencia en ventas',
      'Experiencia en atencion al cliente',
      'Experiencia en ventas por telefono',
      'Experiencia en ventas por WhatsApp',
      'Experiencia en ventas retail',
      'Cumplimiento de metas',
      'Habilidad para negociar',
      'Habilidad para cerrar ventas',
      'Facilidad de palabra',
      'Manejo de caja',
      'Manejo de POS',
      'Manejo de CRM',
      'Manejo de reclamos',
    ],
  },
  {
    id: 'administracion',
    label: 'Administracion',
    items: [
      'Estudios en administracion',
      'Estudios en contabilidad',
      'Experiencia como asistente administrativo',
      'Experiencia como auxiliar contable',
      'Manejo de facturacion',
      'Manejo de archivo',
      'Manejo de cuentas por cobrar',
      'Manejo de cuentas por pagar',
      'Conciliaciones bancarias',
      'Manejo de Excel',
      'Manejo de sistemas contables',
      'Orden y confidencialidad',
      'Capacidad de analisis',
    ],
  },
  {
    id: 'logistica',
    label: 'Bodega y logistica',
    items: [
      'Experiencia en bodega',
      'Experiencia en inventario',
      'Experiencia en logistica',
      'Experiencia en despacho',
      'Recepcion de mercaderia',
      'Carga y descarga',
      'Control de inventarios',
      'Conocimiento de kardex',
      'Licencia de conducir vigente',
      'Experiencia como conductor',
      'Experiencia como repartidor',
      'Capacidad para usar GPS',
      'Manejo de Google Maps',
    ],
  },
  {
    id: 'restaurante',
    label: 'Restaurantes',
    items: [
      'Experiencia como mesero',
      'Experiencia como cajero',
      'Experiencia como barista',
      'Experiencia como cocinero',
      'Experiencia como auxiliar de cocina',
      'Manipulacion higienica de alimentos',
      'Tarjeta de salud vigente',
      'Rapidez y orden',
      'Manejo de pedidos',
      'Atencion amable al cliente',
      'Conocimiento de normas de higiene',
    ],
  },
  {
    id: 'tecnologia',
    label: 'Tecnologia',
    items: [
      'Estudios en sistemas o informatica',
      'Experiencia en soporte tecnico',
      'Mantenimiento de computadoras',
      'Conocimiento de redes',
      'Conocimiento de Windows',
      'Conocimiento de Linux',
      'Conocimiento de SQL',
      'Conocimiento de JavaScript',
      'Conocimiento de HTML y CSS',
      'Conocimiento de React',
      'Conocimiento de Node.js',
      'Manejo de APIs REST',
      'Conocimiento de Git y GitHub',
    ],
  },
  {
    id: 'seguridad',
    label: 'Seguridad',
    items: [
      'Experiencia como guarda de seguridad',
      'Record de policia actualizado',
      'Buena condicion fisica',
      'Disponibilidad para turnos de 12 horas',
      'Disponibilidad para turno nocturno',
      'Control de acceso',
      'Manejo de bitacoras',
      'Protocolos de seguridad',
      'Experiencia en vigilancia',
      'Experiencia en monitoreo de camaras',
      'Primeros auxilios deseable',
    ],
  },
  {
    id: 'limpieza',
    label: 'Limpieza',
    items: [
      'Experiencia en limpieza',
      'Experiencia en mantenimiento general',
      'Conocimiento de productos de limpieza',
      'Buena condicion fisica',
      'Experiencia en limpieza de oficinas',
      'Experiencia en limpieza residencial',
      'Experiencia en limpieza industrial',
      'Conocimiento basico de electricidad',
      'Conocimiento basico de fontaneria',
      'Conocimiento basico de pintura',
    ],
  },
];

export const BENEFIT_CATEGORIES: PresetCategory[] = [
  {
    id: 'basicos',
    label: 'Basicos',
    items: [
      'Salario fijo',
      'Salario competitivo',
      'Pago puntual',
      'Contrato laboral',
      'Prestaciones de ley',
      'Afiliacion al INSS',
      'Vacaciones pagadas',
      'Descanso semanal',
      'Pago de horas extras',
      'Estabilidad laboral',
      'Buen clima laboral',
      'Uniforme',
      'Equipo de trabajo',
      'Capacitacion constante',
      'Oportunidad de crecimiento',
    ],
  },
  {
    id: 'bonos',
    label: 'Bonos e incentivos',
    items: [
      'Bonos por desempeno',
      'Bonos por metas',
      'Bonos por asistencia',
      'Bonos por puntualidad',
      'Bonos por productividad',
      'Comisiones',
      'Comisiones sin techo',
      'Incentivos mensuales',
      'Incentivos semanales',
      'Premios por cumplimiento de metas',
    ],
  },
  {
    id: 'movilidad',
    label: 'Movilidad y apoyo',
    items: [
      'Viaticos',
      'Subsidio de transporte',
      'Subsidio de alimentacion',
      'Alimentacion incluida',
      'Merienda',
      'Almuerzo',
      'Parqueo',
      'Transporte empresarial',
      'Ruta de transporte',
      'Telefono corporativo',
      'Plan de datos',
      'Computadora corporativa',
    ],
  },
  {
    id: 'flexibilidad',
    label: 'Flexibilidad',
    items: [
      'Horario flexible',
      'Jornada de lunes a viernes',
      'Jornada de lunes a sabado',
      'Medio dia sabado',
      'Modalidad hibrida',
      'Modalidad remota',
      'Permisos personales',
      'Permisos por estudio',
      'Permisos por emergencia familiar',
    ],
  },
  {
    id: 'tecnologia',
    label: 'Tecnologia',
    items: [
      'Trabajo remoto',
      'Home office',
      'Acceso a herramientas pagadas',
      'Certificaciones pagadas',
      'Cursos tecnicos',
      'Mentoria',
      'Revisiones salariales',
      'Acceso a plataformas de aprendizaje',
      'Participacion en proyectos internacionales',
    ],
  },
  {
    id: 'ventas',
    label: 'Ventas',
    items: [
      'Comisiones por ventas',
      'Bonos por nuevos clientes',
      'Bonos por recuperacion de cartera',
      'Leads proporcionados por la empresa',
      'Capacitacion en ventas',
      'Capacitacion en producto',
      'Material publicitario',
      'Combustible',
      'Depreciacion de vehiculo',
      'Premios por mejor vendedor',
    ],
  },
  {
    id: 'restaurante',
    label: 'Restaurantes',
    items: [
      'Propinas',
      'Descuentos en consumo',
      'Transporte nocturno',
      'Capacitacion en servicio al cliente',
      'Capacitacion en cocina',
      'Ambiente dinamico',
      'Pago de horas extras',
      'Oportunidad de crecimiento a encargado',
    ],
  },
  {
    id: 'seguridad',
    label: 'Seguridad y campo',
    items: [
      'Equipo de seguridad',
      'Pago de turno nocturno',
      'Capacitacion en seguridad',
      'Capacitacion en primeros auxilios',
      'Descansos programados',
      'Seguro contra accidentes',
      'Equipo de proteccion',
    ],
  },
];
